--!strict
-- Pure authored campaign. No random required geometry and no external dependencies.
local definitions = {
  {
    id = "riverbank_welcome",
    canonicalName = "RiverbankWelcome",
    displayName = "Riverbank Welcome",
    zone = 1,
    primaryMechanic = "Stepping stones",
    teachingGoal = "Follow the arrows. Jump the little gap!",
    role = "teach",
    difficultyTier = 1,
    expectedNoviceSeconds = 25,
  },
  {
    id = "mole_burrow_bounce",
    canonicalName = "MoleBurrowBounce",
    displayName = "Mole Burrow Bounce",
    zone = 1,
    primaryMechanic = "Bounce pads",
    teachingGoal = "Try the spring. The catch floor is safe.",
    role = "practice",
    difficultyTier = 1,
    expectedNoviceSeconds = 35,
  },
  {
    id = "ratty_river_stones",
    canonicalName = "RattyRiverStones",
    displayName = "Ratty River Stones",
    zone = 1,
    primaryMechanic = "Moving logs",
    teachingGoal = "Watch the slow raft, or take the broad stones.",
    role = "twist",
    difficultyTier = 1,
    expectedNoviceSeconds = 35,
  },
  {
    id = "toad_hall_gate",
    canonicalName = "ToadHallGate",
    displayName = "Toad Hall Gate",
    zone = 1,
    primaryMechanic = "Sweeper gate",
    teachingGoal = "Wait in the bay for the sweeper.",
    role = "teach",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "library_tumble",
    canonicalName = "LibraryTumble",
    displayName = "Library Tumble",
    zone = 1,
    primaryMechanic = "Timed shelves",
    teachingGoal = "Yellow means wait; red means active.",
    role = "practice",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "runaway_caravan",
    canonicalName = "RunawayCaravan",
    displayName = "Runaway Caravan",
    zone = 1,
    primaryMechanic = "Conveyor hops",
    teachingGoal = "Ride forward and keep steering.",
    role = "twist",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "tavern_barrel_hop",
    canonicalName = "TavernBarrelHop",
    displayName = "Tavern Barrel Hop",
    zone = 2,
    primaryMechanic = "Barrel hops",
    teachingGoal = "Hop over the silly barrels.",
    role = "teach",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "courtroom_chaos",
    canonicalName = "CourtroomChaos",
    displayName = "Courtroom Chaos",
    zone = 2,
    primaryMechanic = "Gavel timing",
    teachingGoal = "Watch the warning before crossing.",
    role = "practice",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "jailbreak_bars",
    canonicalName = "JailbreakBars",
    displayName = "Jailbreak Bars",
    zone = 2,
    primaryMechanic = "Timed gates",
    teachingGoal = "Count down, then cross the open bars.",
    role = "twist",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "laundry_cart_escape",
    canonicalName = "LaundryCartEscape",
    displayName = "Laundry Cart Escape",
    zone = 2,
    primaryMechanic = "Optional cart",
    teachingGoal = "Walk beside the laundry or try the cart.",
    role = "relief",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "barge_crossing",
    canonicalName = "BargeCrossing",
    displayName = "Barge Crossing",
    zone = 2,
    primaryMechanic = "Moving barge",
    teachingGoal = "Use the docks and slow boats.",
    role = "practice",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "train_tunnel_dash",
    canonicalName = "TrainTunnelDash",
    displayName = "Train Tunnel Dash",
    zone = 2,
    primaryMechanic = "Train timing",
    teachingGoal = "Stay on the sidewalk when the train comes.",
    role = "twist",
    difficultyTier = 2,
    expectedNoviceSeconds = 35,
  },
  {
    id = "wild_wood_gusts",
    canonicalName = "WildWoodGusts",
    displayName = "Wild Wood Gusts",
    zone = 3,
    primaryMechanic = "Wind lanes",
    teachingGoal = "Follow the wind arrows between the rails.",
    role = "teach",
    difficultyTier = 3,
    expectedNoviceSeconds = 35,
  },
  {
    id = "badger_lantern_path",
    canonicalName = "BadgerLanternPath",
    displayName = "Badger Lantern Path",
    zone = 3,
    primaryMechanic = "Lantern walk",
    teachingGoal = "Follow the warm lanterns home.",
    role = "relief",
    difficultyTier = 1,
    expectedNoviceSeconds = 25,
  },
  {
    id = "motorcar_madness",
    canonicalName = "MotorcarMadness",
    displayName = "Motorcar Madness",
    zone = 3,
    primaryMechanic = "Optional fast lane",
    teachingGoal = "Sidewalk is safe; road is a challenge.",
    role = "twist",
    difficultyTier = 3,
    expectedNoviceSeconds = 35,
  },
  {
    id = "roadside_cone_sprint",
    canonicalName = "RoadsideConeSprint",
    displayName = "Roadside Cone Sprint",
    zone = 3,
    primaryMechanic = "Cone sprint",
    teachingGoal = "Weave around the wobbly cones.",
    role = "teach",
    difficultyTier = 3,
    expectedNoviceSeconds = 35,
  },
  {
    id = "homecoming_ring_run",
    canonicalName = "HomecomingRingRun",
    displayName = "Homecoming Ring Run",
    zone = 3,
    primaryMechanic = "Ring recap",
    teachingGoal = "One last gentle jump. Rings are optional!",
    role = "practice",
    difficultyTier = 3,
    expectedNoviceSeconds = 35,
  },
  {
    id = "toad_hall_fireworks",
    canonicalName = "ToadHallFireworks",
    displayName = "Toad Hall Fireworks",
    zone = 3,
    primaryMechanic = "Victory lap",
    teachingGoal = "Welcome home! Your retries made the story.",
    role = "relief",
    difficultyTier = 1,
    expectedNoviceSeconds = 25,
  },
}
for index, definition in ipairs(definitions) do
  definition.index = index
  definition.analyticsLevelName = definition.canonicalName
  definition.path =
    { length = 96, width = 14, landing = 14, maxGap = index <= 3 and 4 or (index <= 12 and 6 or 7.5), maxStep = 4 }
  definition.movement = { periodSeconds = index == 12 and 7 or 5, speed = index <= 3 and 6 or 8 }
  definition.warningSeconds = 0.9
  definition.fallingDelay = 1.5
  definition.assist = { hintFailures = 2, graceFailures = 3, helpFailures = 5, struggleSeconds = 90 }
  definition.optionalChallenge = { enabled = index ~= 18, label = "Optional golden detour", z = 22 }
  definition.collectible = { x = 48, y = 4, z = 22 }
end
return definitions
