local WorldGenConfig = {
  StageTypes = {
    "RiverbankWelcome",
    "MoleBurrowBounce",
    "RattyRiverStones",
    "ToadHallGate",
    "LibraryTumble",
    "RunawayCaravan",
    "TavernBarrelHop",
    "CourtroomChaos",
    "JailbreakBars",
    "LaundryCartEscape",
    "BargeCrossing",
    "TrainTunnelDash",
    "WildWoodGusts",
    "BadgerLanternPath",
    "MotorcarMadness",
    "RoadsideConeSprint",
    "HomecomingRingRun",
    "ToadHallFireworks",
  },
  StageDisplayNames = {
    RiverbankWelcome = "Riverbank Welcome",
    MoleBurrowBounce = "Mole's Burrow Bounce",
    RattyRiverStones = "Ratty's River Stones",
    ToadHallGate = "Toad Hall Gate",
    LibraryTumble = "Library Tumble",
    RunawayCaravan = "Runaway Caravan",
    TavernBarrelHop = "Tavern Barrel Hop",
    CourtroomChaos = "Courtroom Chaos",
    JailbreakBars = "Jailbreak Bars",
    LaundryCartEscape = "Laundry Cart Escape",
    BargeCrossing = "Barge Crossing",
    TrainTunnelDash = "Train Tunnel Dash",
    WildWoodGusts = "Wild Wood Gusts",
    BadgerLanternPath = "Badger's Lantern Path",
    MotorcarMadness = "Motorcar Madness",
    RoadsideConeSprint = "Roadside Cone Sprint",
    HomecomingRingRun = "Homecoming Ring Run",
    ToadHallFireworks = "Toad Hall Fireworks",
  },
  StageLengthMin = 40,
  StageLengthMax = 60,
  PlatformSize = Vector3.new(10, 1, 10),
  PathWidth = 22,
  CheckpointSize = Vector3.new(6, 1, 6),
  LaneLightSpacing = 12,
}

return WorldGenConfig
