#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
fail() { echo "FAIL: $*" >&2; exit 1; }

grep -q 'Name = "GeneratedObby"' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "generated ownership root missing"
grep -q 'GeneratorOwner' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "generator ownership marker missing"
grep -q 'GeneratorVersion = "2"' "$ROOT_DIR/src/shared/Config/WorldGenConfig.lua" || fail "canonical generator version missing"
grep -q 'unsupported generator version' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "generator version validation missing"
grep -q 'generated root has an invalid seed' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "generated root seed validation missing"
grep -q 'not parented to Workspace' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "generated root parent validation missing"
grep -q 'Refusing to delete Workspace.GeneratedObby' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "rebuild ownership guard missing"
grep -q 'Invalid world seed' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "world seed boundary validation missing"
grep -q 'seed ~= seed' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "NaN seed rejection missing"
grep -q 'stageId = result.model:GetAttribute("StageId")' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "stage manifest IDs missing"
grep -q 'connectorLength = connectorLength' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "stage connector measurements missing"
grep -q 'previousExit = args.previousExit' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "cross-zone connector origin missing"
grep -q 'previousExit = previousZoneExit' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "world builder does not pass prior zone exit"
grep -q 'local zones = {}' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "world zone manifest missing"
grep -q 'zones = zones' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "world zone manifest is not returned"
grep -q 'validate(allStages, totalStages, zones, obbyModel)' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "zone manifest is not validated"
grep -q 'function validateZones' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "zone validator missing"
grep -q 'center = zoneCFrame.Position' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "zone center is not exposed"
grep -q 'zoneIndex = args.zoneIndex' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "stage zone ownership missing"
grep -q 'local modelIsModel = typeof(stageModel) == "Instance"' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator model guard missing"
grep -q 'if typeof(stage.model) == "Instance" and stage.model:IsA("Model")' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator descendant guard missing"
grep -q 'if stage.checkpoint and stage.checkpoint:IsA("BasePart")' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator checkpoint guard missing"
grep -q 'typeof(stage.entrance) == "CFrame"' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator CFrame type guards missing"
grep -q 'finiteVector(stage.bounds)' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator finite geometry guard missing"
grep -q 'stage.stageIndex % 1 == 0' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator stage index integer guard missing"
grep -q 'stageLabel(stage)' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator diagnostic formatting is not malformed-input safe"
grep -q 'type(stage.stageId) ~= "string"' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator stage ID type guard missing"
grep -q 'stable ID does not match canonical configuration' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator canonical stage ID check missing"
grep -q 'type does not match canonical configuration' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator canonical stage type check missing"
grep -q 'incorrect zone ownership' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator zone ownership check missing"
grep -q 'model is outside its expected zone' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator model zone check missing"
grep -q 'model ID differs from manifest' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator model ID check missing"
grep -q 'model index differs from manifest' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator model index check missing"
grep -q 'SetAttribute("ZoneIndex", args.zoneIndex)' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "stage model zone marker missing"
grep -q 'zoneModel = zoneModel' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "stage zone container reference missing"
grep -q 'pathCorridor = result.pathCorridor' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "stage path corridor missing"
grep -q 'missing a valid path corridor' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator path corridor check missing"
grep -q 'validMechanics' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator mechanic metadata check missing"
grep -q 'not parented to its zone model' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator zone hierarchy check missing"
grep -q 'missing a valid zone model' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator missing-zone fail-closed check missing"
grep -q 'not measured correctly' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator connector measurement check missing"
grep -q 'typeof(stageModel) == "Instance"' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator instance type guards missing"
grep -q 'local owned = false' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator collectible ownership scope missing"
grep -q 'normalizeCheckpoint' "$ROOT_DIR/src/shared/Util/ProgressionRules.lua" || fail "checkpoint normalization guard missing"
grep -q 'ProgressionRules.canAdvance' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "shared progression rules are not authoritative"
grep -q 'function ProgressionRules.canAdvance' "$ROOT_DIR/src/shared/Util/ProgressionRules.lua" || fail "pure progression rule missing"
if grep -q 'part:Destroy()' "$ROOT_DIR/src/server/Services/ObbyService.lua"; then
  fail "collectible runtime must not globally destroy keys"
fi
grep -q 'GeneratorVersion' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "generator version missing"
grep -q 'AuthoredKeysPerChapter = 1' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "authored key contract missing"
grep -q 'GetObbyState' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "initial state request missing"
if grep -q 'progressEvent:FireAllClients' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua"; then fail "startup state must not broadcast globally"; fi
if grep -q 'celebrator.Parent = checkpoint' "$ROOT_DIR/src/server/Services/CheckpointService.lua"; then fail "finale burst must not be shared"; fi
grep -q 'SetAccessibilitySettings' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "settings contract missing"
grep -q 'runStarted: boolean?' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "progress timer contract missing"
grep -q 'keyId = keyId' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key feedback identity missing"
grep -q 'function UIController:hideCollectedKey' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "per-player key presentation hiding is missing"
grep -q 'payload.collectedKeys' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "initial collected-key state is not applied"
grep -q 'GetInstanceAddedSignal("KeyCollectible")' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "streamed collectible visibility is not reconciled"
grep -q 'reducedMotion = true' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "settings allowlist missing"
grep -q 'if not self.checkpoints:isLoaded(player) then' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "remote profile readiness guard missing"
grep -q 'Magnitude <= 18' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint distance validation missing"
grep -q 'Magnitude > 18' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key distance validation missing"
grep -q 'SetRunMode' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "run mode contract missing"
grep -q 'completionCount < 1' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "time trial unlock guard missing"
grep -q 'MinimumTimeTrialSeconds' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "time trial plausibility threshold missing"
grep -q 'elapsed < self.minimumTimeTrialSeconds' "$ROOT_DIR/src/server/Services/RunStateService.lua" || fail "implausibly fast trials are not rejected"
grep -q 'player:SetAttribute("RunCompleted", false)' "$ROOT_DIR/src/server/Services/RunStateService.lua" || fail "run completion state is not reset"
grep -q 'humanoid.Health <= 0' "$ROOT_DIR/src/server/Services/RunStateService.lua" || fail "time trial gate accepts dead characters"
grep -q 'local function getLivePlayerRoot' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "physics touch authority helper missing"
grep -q 'inst:IsDescendantOf(self.world.model)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "behavior scan is not ownership-scoped"
grep -q 'RunStartGate' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "time trial start gate missing"
grep -q 'startAtGate' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "server time trial gate handling missing"
grep -q 'resetForTimeTrial' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "time trial checkpoint reset missing"
grep -q 'resetForTimeTrial(player)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "time trial gate does not reset progress"
grep -q 'resetForAdventure(player)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "adventure replay does not reset progress"
grep -q 'function CheckpointService:resetForAdventure' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "adventure reset authority is missing"
grep -q 'if mode == "TimeTrial" then' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "time trial mode reset missing"
grep -q 'self.modeEvent:FireServer("TimeTrial")' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "time trial reset control missing"
grep -q 'SetPracticeStage' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "practice stage contract missing"
grep -q 'bestChapterMs: table' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "finale payload contract is incomplete"
grep -q 'profile.highestChapter < stage' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "practice stage progression guard missing"
grep -q 'lowParticles = false' "$ROOT_DIR/src/shared/Config/ProfileSchema.lua" || fail "complete accessibility profile defaults missing"
grep -q 'AnalyticsService' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "analytics service wiring missing"
grep -q 'LogCustomEvent' "$ROOT_DIR/src/server/Services/AnalyticsService.lua" || fail "analytics events are not submitted"
grep -q 'analytics:track(player, "chapter_started"' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "chapter start analytics event missing"
grep -q 'bestChapterMs\[splitKey\]' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "chapter split persistence missing"
grep -q 'player:GetAttribute("RunMode") == "TimeTrial"' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "adventure completion can overwrite time trial best"
grep -q 'merged.collectedKeys' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "concurrent key merge missing"
grep -q 'mergeKeys(value.collectedKeys)' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "bounded value key merge missing"
grep -q 'mergeKeys(current.collectedKeys)' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "bounded current key merge missing"
grep -q 'ProfileSchema.MaxCounter' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "stored counter merge is not bounded"
grep -q 'ProfileSchema.MaxChapter' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "stored chapter merge is not bounded"
grep -q 'merged.bestChapterMs' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "concurrent chapter split merge missing"
grep -q 'chapterNumber <= 18' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "chapter split merge is not bounded"
grep -q 'merged.settings' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "concurrent settings merge missing"
grep -q 'masterVolume", "musicVolume", "sfxVolume", "uiScale' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "numeric settings merge missing"
grep -q 'showResults' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results presentation missing"
grep -q 'TimeTrialButton' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results replay actions missing"
grep -q 'Golden Keys' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results key metric missing"
grep -q 'Route completion: 100%%' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results route completion metric missing"
grep -q 'Exploration:' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results exploration metric missing"
grep -q 'showPracticeSelector' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "practice selector missing"
grep -q 'if actionMode == "Practice" then' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results practice action bypasses selector"
grep -q 'function UIController:updateTimerState' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "time trial HUD timer missing"
grep -q 'runStarted = mode ~= "TimeTrial"' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "timer start state not synchronized"
grep -q 'AutomaticCanvasSize = Enum.AutomaticSize.Y' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "settings panel is not responsive"
if grep -q 'MouseButton1Click' "$ROOT_DIR/src/client/Controllers/UIController.lua"; then fail "HUD controls use mouse-only activation"; fi
grep -q 'reset.Selectable = true' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "reset button gamepad selection missing"
grep -q 'button.Selectable = true' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "replay button gamepad selection missing"
grep -q 'cardConstraint.MinSize = Vector2.new(280, 220)' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results card has no responsive minimum"
grep -q 'buttonConstraint.MinSize = Vector2.new(84, 44)' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results actions miss touch target minimum"
grep -q 'math.max(self.highestChapter, stage)' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "practice unlock state is not live-synchronized"
grep -q 'highestChapter = self.checkpoints' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "completed chapter state missing"
grep -q 'applyAccessibility' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "accessibility application missing"
grep -q 'function EnvironmentController:syncInitialState' "$ROOT_DIR/src/client/Controllers/EnvironmentController.lua" || fail "environment initial state sync missing"
grep -q 'tween:Cancel()' "$ROOT_DIR/src/client/Controllers/EnvironmentController.lua" || fail "environment tween lifecycle is unbounded"
grep -q 'originalHazardMaterials' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "high contrast material restoration missing"
grep -q 'GetInstanceAddedSignal("KillBrick")' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "streamed hazards miss high contrast mode"
grep -q 'if root and not reducedMotion then' "$ROOT_DIR/src/client/Controllers/EffectsController.lua" || fail "reduced motion still emits finale particles"
grep -q 'MaxDevSeed' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "dev seed cap missing"
grep -q 'SaveCheckpoints = true' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "production persistence default missing"
if grep -q 'MaxPlayersPerServer' "$ROOT_DIR/src/shared/Config/GameConfig.lua"; then fail "fake server capacity knob remains"; fi
grep -q 'player:" .. tostring(player.UserId)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "string datastore key missing"
grep -q 'local saved, loadSucceeded' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "datastore load outcome is not distinguished"
grep -q 'player:SetAttribute("Checkpoint", 0)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "profile load does not establish zero checkpoint state"
grep -q 'if player.Character then' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "profile load does not repair existing character position"
grep -q 'if not player.Parent then' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "profile load lacks leave guard"
grep -q 'not self:isLoaded(player)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "failed profile loads can still be saved"
grep -q 'checkpointProfile.highestChapter = math.max' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint profile state is stale"
grep -Fq 'self.deathConnections[player]:Disconnect()' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "respawn death connections are not cleaned"
grep -q 'profile.highestChapter = math.clamp(math.max(profile.highestChapter' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "save path can regress profile progress"
grep -q 'local snapshot = ProfileSchema.sanitize(profile)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "save path passes mutable profile"
grep -q 'if not self:isLoaded(player) then' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint progression is not load-gated"
grep -q 'if cp and cp:IsA("BasePart") then' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint binding lacks runtime type guard"
grep -q 'WaitForChild("HumanoidRootPart", 5)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint teleport has no bounded root wait"
grep -q 'function CheckpointService:teleportToCFrame' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "mode teleport helper missing"
grep -q 'MaxCollectedKeys = 100' "$ROOT_DIR/src/shared/Config/ProfileSchema.lua" || fail "profile key bound missing"
grep -q 'type(keyId) ~= "string"' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator collectible ID type guard missing"
grep -q 'ProfileSchema.MaxCollectedKeys' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "runtime key bound missing"
grep -q 'profile_contract.sh' "$ROOT_DIR/scripts/check.sh" || fail "profile contract is not in the CI gate"
grep -q 'GetRequestBudgetForRequestType' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "datastore request budget is not checked"
grep -q 'storeName .. "_StudioSandbox"' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "studio sandbox shares production datastore"
grep -q 'DevCommandCooldownSeconds' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "dev command rate limit missing"
grep -q 'for _, player in ipairs(Players:GetPlayers()) do' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "existing players do not receive dev commands"
grep -q 'math.min(GameConfig.MaxDevStage, #self.world.stages)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "dynamic stage command cap missing"
grep -q 'approvedForRelease' "$ROOT_DIR/src/shared/Config/AssetRegistry.lua" || fail "asset approval registry missing"
grep -q 'getApprovedId("checkpoint_feedback")' "$ROOT_DIR/src/shared/Util/Build.lua" || fail "checkpoint sound bypasses asset registry"
grep -q 'getApprovedId("key_pickup")' "$ROOT_DIR/src/shared/Util/Build.lua" || fail "key sound bypasses asset registry"
grep -q 'getApprovedId("finale_firework")' "$ROOT_DIR/src/client/Controllers/EffectsController.lua" || fail "finale particle bypasses asset registry"
grep -q 'getApprovedId("finale_chime")' "$ROOT_DIR/src/client/Controllers/EffectsController.lua" || fail "finale sound bypasses asset registry"
if grep -R -q 'rbxassetid://' "$ROOT_DIR/src/server/WorldGen" "$ROOT_DIR/src/shared/Util"; then fail "generated visual assets bypass registry"; fi
if grep -R -q 'AmbientSoundId' "$ROOT_DIR/src"; then fail "zone ambience bypasses asset registry"; fi
grep -q 'getApprovedId(zoneConfig.AmbientSoundKey)' "$ROOT_DIR/src/server/WorldGen/DecorBuilder.lua" || fail "zone ambience is not approval-gated"
grep -q 'checkpointPulse' "$ROOT_DIR/src/client/Controllers/EffectsController.lua" || fail "checkpoint feedback pulse missing"
if grep -q 'Size = UDim2.fromScale(1, 1)' "$ROOT_DIR/src/client/Controllers/EffectsController.lua"; then fail "ordinary checkpoint feedback must not full-screen flash"; fi
grep -q 'playFirstApprovedMusic' "$ROOT_DIR/src/server/ServerMain.server.lua" || fail "asset approval gate missing"
grep -q 'ChapterFlavor' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "chapter presentation metadata missing"
grep -q 'StageBuildResult' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "explicit stage build result missing"
grep -q 'No stage template registered' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "missing stage templates must fail closed"
grep -q 'did not return a valid exit CFrame' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "invalid template exits must fail closed"
grep -q 'duplicate collectible id' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "duplicate collectible validation missing"
grep -q 'does not progress forward' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "forward geometry validation missing"
grep -q 'unanchored environment part' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "anchored environment validation missing"
grep -q 'PhysicsDecor' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "intentional physics decoration marker missing"
grep -q 'insufficient standing room' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "checkpoint standing-room validation missing"
grep -q 'overlaps hazard' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "checkpoint hazard-overlap validation missing"
grep -q 'failed validation with' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "invalid generated worlds are not rejected"
grep -q 'expected %d stages, found %d' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "stage count validation missing"
grep -q 'duplicate or invalid stage index' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "stage index uniqueness validation missing"
grep -q 'wrong stable stage ID' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "checkpoint stable ID validation missing"
grep -q 'checkpoint is outside its model' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "checkpoint ownership validation missing"
grep -q 'rejected invalid runtime checkpoint' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "runtime checkpoint identity validation missing"
grep -q 'timedOut = item.elapsed > 45' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cart timeout recovery missing"
grep -q 'stageIndex < 1 or stageIndex > self.totalStages' "$ROOT_DIR/src/server/Services/RunStateService.lua" || fail "run stage bounds missing"
grep -q 'occupant.Sit = false' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cart reset does not safely dismount riders"
grep -q 'SetNetworkOwner(nil)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "respawn network ownership reset missing"
grep -q 'shutdownBound' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "shutdown callback lifecycle guard missing"
grep -q 'local direction = part.CFrame.LookVector' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "conveyor vertical velocity handling missing"
grep -q 'if item.part and item.part.Parent then' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "obstacle lifecycle guards missing"
grep -q 'part:SetNetworkOwner(nil)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cart network ownership is not server-controlled"
grep -q 'item.seat and item.seat.Occupant ~= nil' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cart motion is not occupant-gated"
grep -q 'Build.cart(ctx.origin \* CFrame.new(5, 1.5, 0), model)' "$ROOT_DIR/src/server/WorldGen/Templates/StageTemplates.lua" || fail "laundry chapter lacks signature cart"
grep -q 'startGate = startGate' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "time trial start gate is not exposed"
grep -q 'teleportToCFrame(player' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "time trial selection does not return to start"
grep -q 'setPracticeCheckpoint(player, stage)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "practice stage does not establish a temporary respawn checkpoint"
grep -q 'function CheckpointService:setPracticeCheckpoint' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "practice checkpoint authority is missing"
grep -q 'showTimer = "Show Time Trial timer"' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "timer visibility setting is missing"
grep -q 'function UIController:applyAudioVolumes' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "local audio volume mixing is missing"
grep -q 'function UIController:refreshVolumeLabels' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "audio control labels are not synchronized"
grep -q 'self:updateTimerState(payload)' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "initial timer state sync missing"
grep -q 'masterVolume = "volume"' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "numeric audio settings are not server-validated"
grep -q 'function UIController:applyUIScale' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "persisted UI scale is not applied"
grep -q 'uiScale = "scale"' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "UI scale is not server-validated"
grep -q 'SoundGroups.ensure("Music"' "$ROOT_DIR/src/server/ServerMain.server.lua" || fail "Music SoundGroup is missing"
grep -q 'SoundGroups.ensure("Ambience"' "$ROOT_DIR/src/server/WorldGen/DecorBuilder.lua" || fail "Ambience SoundGroup is missing"
grep -q 'SoundGroups.ensure("SFX"' "$ROOT_DIR/src/shared/Util/Build.lua" || fail "SFX SoundGroup is missing"
grep -q 'SoundGroup = SoundGroups.ensure("Music"' "$ROOT_DIR/src/server/ServerMain.server.lua" || fail "music is not routed through Music group"
grep -q 'SoundGroup = SoundGroups.ensure("Ambience"' "$ROOT_DIR/src/server/WorldGen/DecorBuilder.lua" || fail "ambience is not routed through Ambience group"
grep -q 'sound.SoundGroup = SoundGroups.ensure("SFX"' "$ROOT_DIR/src/shared/Util/Build.lua" || fail "gameplay feedback is not routed through SFX group"
grep -q 'addLandmark(zoneModel, zoneConfig, zoneCFrame.Position, zoneSize)' "$ROOT_DIR/src/server/WorldGen/DecorBuilder.lua" || fail "zone-relative landmark layer is missing"
grep -q 'non-finite entrance or exit' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "zone entrance/exit finiteness validation missing"
grep -q 'invalid center' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "zone center validation missing"
grep -q 'CanQuery = false' "$ROOT_DIR/src/server/WorldGen/DecorBuilder.lua" || fail "landmark collision/query budget is not disabled"
grep -q 'hasNearbyPlayer(item.part.Position, 180)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "non-critical proximity activation is missing"
grep -q 'TextChatCommand' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "modern developer command path is missing"
grep -q 'PrimaryAlias = definition.alias' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "developer command aliases are not explicit"
grep -q 'self.cosmeticClock >= 1 / 30' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cosmetic obstacle updates are not bounded"
grep -q 'gameplayTags' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cosmetic beacons can move gameplay parts"
grep -q 'self.checkpoints:destroy()' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rebuild checkpoint teardown missing"
grep -q 'self.queryClock = 0' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rebuild runtime clocks are not reset"
grep -q 'movedCharacters' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "moving platform rider deduplication missing"
grep -q 'riderQueryClock >= 0.05' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "moving platform queries are not bounded"
grep -q 'self.riderQueryClock = 0' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rider query clock is not reset on rebuild"
grep -q 'lastCall\[player\] = nil' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rate-limit player cleanup missing"
grep -q 'currentVelocity.Y' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "moving platform vertical velocity preservation missing"
grep -q 'Players:GetPlayerFromCharacter(character)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "hazard interaction is not player-context validated"
grep -q 'lastHit\[humanoid\]' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "hazard touch debounce missing"
grep -q '__mode = "k"' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "hazard debounce table can retain dead humanoids"
grep -q 'function CheckpointService:isLoaded' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "profile readiness check missing"
grep -q 'ProfileLoadStatus' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "profile load status visibility missing"
grep -q 'ToadsPlayers' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "multiplayer player collision group missing"
grep -q 'CollisionGroupSetCollidable' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "player collision isolation missing"
grep -q 'character.DescendantAdded' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "late character parts miss collision isolation"
grep -q 'highestChapter = self:getProfile(player).highestChapter' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "initial highest chapter sync missing"
grep -q 'highestChapter = self.checkpoints and self.checkpoints:getProfile(player).highestChapter' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "state highest chapter sync missing"
grep -q 'ProfileSaveStatus' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "profile save status visibility missing"
grep -q 'ephemeral profile' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "datastore failure playability path missing"
grep -q 'persistenceAllowed' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "failed reads are not write-gated"
grep -q 'normalizeCheckpoint(player:GetAttribute("Checkpoint"))' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "save checkpoint normalization missing"
grep -q 'function Wrapper:isEnabled' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "datastore environment visibility missing"
grep -q 'self.checkpoints:isLoaded(player)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key collection can race profile load"
grep -q '#keyId > 80' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key identity bounds missing"
echo "production contracts ok"
