#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
fail() { echo "FAIL: $*" >&2; exit 1; }

grep -q 'Name = "GeneratedObby"' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "generated ownership root missing"
grep -q 'GeneratorOwner' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "generator ownership marker missing"
grep -q 'Refusing to delete Workspace.GeneratedObby' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "rebuild ownership guard missing"
grep -q 'Invalid world seed' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "world seed boundary validation missing"
grep -q 'seed ~= seed' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "NaN seed rejection missing"
grep -q 'stageId = result.model:GetAttribute("StageId")' "$ROOT_DIR/src/server/WorldGen/ZoneBuilder.lua" || fail "stage manifest IDs missing"
grep -q 'if not stageModel or not stageModel:IsA("Model")' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator model guard missing"
grep -q 'if stage.model and stage.model:IsA("Model")' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator descendant guard missing"
grep -q 'if stage.checkpoint and stage.checkpoint:IsA("BasePart")' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "validator checkpoint guard missing"
grep -q 'stageIndex <= previous' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint regression guard missing"
if grep -q 'part:Destroy()' "$ROOT_DIR/src/server/Services/ObbyService.lua"; then
  fail "collectible runtime must not globally destroy keys"
fi
grep -q 'GeneratorVersion' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "generator version missing"
grep -q 'AuthoredKeysPerChapter = 1' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "authored key contract missing"
grep -q 'GetObbyState' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "initial state request missing"
if grep -q 'progressEvent:FireAllClients' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua"; then fail "startup state must not broadcast globally"; fi
if grep -q 'celebrator.Parent = checkpoint' "$ROOT_DIR/src/server/Services/CheckpointService.lua"; then fail "finale burst must not be shared"; fi
grep -q 'SetAccessibilitySettings' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "settings contract missing"
grep -q 'runStarted: boolean?' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "progress timer contract missing"
grep -q 'keyId = keyId' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key feedback identity missing"
grep -q 'reducedMotion = true' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "settings allowlist missing"
grep -q 'if not self.checkpoints:isLoaded(player) then' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "remote profile readiness guard missing"
grep -q 'Magnitude <= 18' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint distance validation missing"
grep -q 'Magnitude > 18' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key distance validation missing"
grep -q 'SetRunMode' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "run mode contract missing"
grep -q 'completionCount < 1' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "time trial unlock guard missing"
grep -q 'MinimumTimeTrialSeconds' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "time trial plausibility threshold missing"
grep -q 'elapsed < self.minimumTimeTrialSeconds' "$ROOT_DIR/src/server/Services/RunStateService.lua" || fail "implausibly fast trials are not rejected"
grep -q 'player:SetAttribute("RunCompleted", false)' "$ROOT_DIR/src/server/Services/RunStateService.lua" || fail "run completion state is not reset"
grep -q 'RunStartGate' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "time trial start gate missing"
grep -q 'startAtGate' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "server time trial gate handling missing"
grep -q 'resetForTimeTrial' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "time trial checkpoint reset missing"
grep -q 'resetForTimeTrial(player)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "time trial gate does not reset progress"
grep -q 'if mode == "TimeTrial" then' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "time trial mode reset missing"
grep -q 'self.modeEvent:FireServer("TimeTrial")' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "time trial reset control missing"
grep -q 'SetPracticeStage' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "practice stage contract missing"
grep -q 'bestChapterMs: table' "$ROOT_DIR/src/shared/Network/RemoteContracts.lua" || fail "finale payload contract is incomplete"
grep -q 'profile.highestChapter < stage' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "practice stage progression guard missing"
grep -q 'lowParticles = false' "$ROOT_DIR/src/shared/Config/ProfileSchema.lua" || fail "complete accessibility profile defaults missing"
grep -q 'AnalyticsService' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "analytics service wiring missing"
grep -q 'bestChapterMs\[splitKey\]' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "chapter split persistence missing"
grep -q 'merged.collectedKeys' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "concurrent key merge missing"
grep -q 'mergeKeys(value.collectedKeys)' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "bounded value key merge missing"
grep -q 'mergeKeys(current.collectedKeys)' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "bounded current key merge missing"
grep -q 'merged.bestChapterMs' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "concurrent chapter split merge missing"
grep -q 'merged.settings' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "concurrent settings merge missing"
grep -q 'showResults' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results presentation missing"
grep -q 'TimeTrialButton' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results replay actions missing"
grep -q 'Golden Keys' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "results key metric missing"
grep -q 'showPracticeSelector' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "practice selector missing"
grep -q 'function UIController:updateTimerState' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "time trial HUD timer missing"
grep -q 'runStarted = mode ~= "TimeTrial"' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "timer start state not synchronized"
grep -q 'AutomaticCanvasSize = Enum.AutomaticSize.Y' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "settings panel is not responsive"
if rg -q 'MouseButton1Click' "$ROOT_DIR/src/client/Controllers/UIController.lua"; then fail "HUD controls use mouse-only activation"; fi
grep -q 'reset.Selectable = true' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "reset button gamepad selection missing"
grep -q 'button.Selectable = true' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "replay button gamepad selection missing"
grep -q 'math.max(self.highestChapter, stage)' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "practice unlock state is not live-synchronized"
grep -q 'highestChapter = self.checkpoints' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "completed chapter state missing"
grep -q 'applyAccessibility' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "accessibility application missing"
grep -q 'function EnvironmentController:syncInitialState' "$ROOT_DIR/src/client/Controllers/EnvironmentController.lua" || fail "environment initial state sync missing"
grep -q 'tween:Cancel()' "$ROOT_DIR/src/client/Controllers/EnvironmentController.lua" || fail "environment tween lifecycle is unbounded"
grep -q 'originalHazardMaterials' "$ROOT_DIR/src/client/Controllers/UIController.lua" || fail "high contrast material restoration missing"
grep -q 'MaxDevSeed' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "dev seed cap missing"
grep -q 'SaveCheckpoints = true' "$ROOT_DIR/src/shared/Config/GameConfig.lua" || fail "production persistence default missing"
if grep -q 'MaxPlayersPerServer' "$ROOT_DIR/src/shared/Config/GameConfig.lua"; then fail "fake server capacity knob remains"; fi
grep -q 'player:" .. tostring(player.UserId)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "string datastore key missing"
grep -q 'local saved, loadSucceeded' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "datastore load outcome is not distinguished"
grep -q 'not self:isLoaded(player)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "failed profile loads can still be saved"
grep -q 'checkpointProfile.highestChapter = math.max' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint profile state is stale"
grep -q 'if not self:isLoaded(player) then' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "checkpoint progression is not load-gated"
grep -q 'MaxCollectedKeys = 100' "$ROOT_DIR/src/shared/Config/ProfileSchema.lua" || fail "profile key bound missing"
grep -q 'ProfileSchema.MaxCollectedKeys' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "runtime key bound missing"
grep -q 'profile_contract.sh' "$ROOT_DIR/scripts/check.sh" || fail "profile contract is not in the CI gate"
grep -q 'GetRequestBudgetForRequestType' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "datastore request budget is not checked"
grep -q 'storeName .. "_StudioSandbox"' "$ROOT_DIR/src/server/Services/DataStoreServiceWrapper.lua" || fail "studio sandbox shares production datastore"
grep -q 'DevCommandCooldownSeconds' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "dev command rate limit missing"
grep -q 'math.min(GameConfig.MaxDevStage, #self.world.stages)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "dynamic stage command cap missing"
grep -q 'approvedForRelease' "$ROOT_DIR/src/shared/Config/AssetRegistry.lua" || fail "asset approval registry missing"
grep -q 'getApprovedId("checkpoint_feedback")' "$ROOT_DIR/src/shared/Util/Build.lua" || fail "checkpoint sound bypasses asset registry"
grep -q 'getApprovedId("key_pickup")' "$ROOT_DIR/src/shared/Util/Build.lua" || fail "key sound bypasses asset registry"
grep -q 'getApprovedId("finale_firework")' "$ROOT_DIR/src/client/Controllers/EffectsController.lua" || fail "finale particle bypasses asset registry"
grep -q 'getApprovedId("finale_chime")' "$ROOT_DIR/src/client/Controllers/EffectsController.lua" || fail "finale sound bypasses asset registry"
if rg -q 'rbxassetid://' "$ROOT_DIR/src/server/WorldGen" "$ROOT_DIR/src/shared/Util"; then fail "generated visual assets bypass registry"; fi
if rg -q 'AmbientSoundId' "$ROOT_DIR/src"; then fail "zone ambience bypasses asset registry"; fi
grep -q 'getApprovedId(zoneConfig.AmbientSoundKey)' "$ROOT_DIR/src/server/WorldGen/DecorBuilder.lua" || fail "zone ambience is not approval-gated"
grep -q 'checkpointPulse' "$ROOT_DIR/src/client/Controllers/EffectsController.lua" || fail "checkpoint feedback pulse missing"
if grep -q 'Size = UDim2.fromScale(1, 1)' "$ROOT_DIR/src/client/Controllers/EffectsController.lua"; then fail "ordinary checkpoint feedback must not full-screen flash"; fi
grep -q 'playFirstApprovedMusic' "$ROOT_DIR/src/server/ServerMain.server.lua" || fail "asset approval gate missing"
grep -q 'ChapterFlavor' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "chapter presentation metadata missing"
grep -q 'StageBuildResult' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "explicit stage build result missing"
grep -q 'No stage template registered' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "missing stage templates must fail closed"
grep -q 'did not return a valid exit CFrame' "$ROOT_DIR/src/server/WorldGen/StageBuilder.lua" || fail "invalid template exits must fail closed"
grep -q 'duplicate collectible id' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "duplicate collectible validation missing"
grep -q 'does not progress forward' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "forward geometry validation missing"
grep -q 'unanchored environment part' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "anchored environment validation missing"
grep -q 'insufficient standing room' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "checkpoint standing-room validation missing"
grep -q 'overlaps hazard' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "checkpoint hazard-overlap validation missing"
grep -q 'failed validation with' "$ROOT_DIR/src/server/WorldGen/WorldBuilder.lua" || fail "invalid generated worlds are not rejected"
grep -q 'expected %d stages, found %d' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "stage count validation missing"
grep -q 'duplicate or invalid stage index' "$ROOT_DIR/src/server/WorldGen/WorldValidator.lua" || fail "stage index uniqueness validation missing"
grep -q 'timedOut = item.elapsed > 45' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cart timeout recovery missing"
grep -q 'SetNetworkOwner(nil)' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "respawn network ownership reset missing"
grep -q 'shutdownBound' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "shutdown callback lifecycle guard missing"
grep -q 'local direction = part.CFrame.LookVector' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "conveyor vertical velocity handling missing"
grep -q 'if item.part and item.part.Parent then' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "obstacle lifecycle guards missing"
grep -q 'part:SetNetworkOwner(nil)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cart network ownership is not server-controlled"
grep -q 'self.cosmeticClock >= 1 / 30' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "cosmetic obstacle updates are not bounded"
grep -q 'self.checkpoints:destroy()' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rebuild checkpoint teardown missing"
grep -q 'self.queryClock = 0' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rebuild runtime clocks are not reset"
grep -q 'movedCharacters' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "moving platform rider deduplication missing"
grep -q 'riderQueryClock >= 0.05' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "moving platform queries are not bounded"
grep -q 'self.riderQueryClock = 0' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rider query clock is not reset on rebuild"
grep -q 'lastCall\[player\] = nil' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "rate-limit player cleanup missing"
grep -q 'currentVelocity.Y' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "moving platform vertical velocity preservation missing"
grep -q 'Players:GetPlayerFromCharacter(character)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "hazard interaction is not player-context validated"
grep -q 'lastHit\[humanoid\]' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "hazard touch debounce missing"
grep -q 'function CheckpointService:isLoaded' "$ROOT_DIR/src/server/Services/CheckpointService.lua" || fail "profile readiness check missing"
grep -q 'self.checkpoints:isLoaded(player)' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key collection can race profile load"
grep -q '#keyId > 80' "$ROOT_DIR/src/server/Services/ObbyService.lua" || fail "key identity bounds missing"
echo "production contracts ok"
